# Generated by Django 6.0.3 on 2026-04-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_orderimage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ['-created_at']},
        ),
    ]
