# Generated by Django 5.2.7 on 2026-04-14 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_alter_order_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='old_settlement_mode',
            field=models.CharField(choices=[('none', 'None'), ('weight', 'By Weight'), ('value', 'By Direct Value')], default='none', max_length=10),
        ),
        migrations.AddField(
            model_name='order',
            name='old_value_direct',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
