# Generated by Django 6.0.3 on 2026-06-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_order_old_deduct_amount_order_old_deduct_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='making_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
