# Generated by Django 6.0.3 on 2026-06-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_order_making_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='making_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
