# Generated by Django 6.0.3 on 2026-07-06 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0009_order_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'Online / UPI'), ('card', 'Card'), ('bank_transfer', 'Bank Transfer')], max_length=50, null=True),
        ),
    ]
