# Generated by Django 6.0.3 on 2026-07-10 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_purchases', '__first__'),
        ('orders', '0011_order_igst'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='old_purchase_voucher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_settlements', to='old_purchases.oldpurchasevoucher'),
        ),
        migrations.AddField(
            model_name='order',
            name='old_voucher_rate_used',
            field=models.CharField(default='saved', max_length=10),
        ),
        migrations.AlterField(
            model_name='order',
            name='old_settlement_mode',
            field=models.CharField(choices=[('none', 'None'), ('weight', 'By Weight'), ('value', 'By Direct Value'), ('voucher', 'By Purchase Voucher')], default='none', max_length=10),
        ),
    ]
