# Generated by Django 6.0.3 on 2026-04-10 19:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='estimate',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='invoice',
            options={'ordering': ['-created_at']},
        ),
    ]
