# Generated by Django 6.0.3 on 2026-05-02 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_estimate_old_settlement_mode_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='old_deduct_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='estimate',
            name='old_deduct_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='estimate',
            name='old_metal_raw_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='estimate',
            name='transaction_type',
            field=models.CharField(choices=[('payable', 'Customer Payable'), ('return', 'Return to Customer')], default='payable', max_length=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='old_deduct_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='old_deduct_percent',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AddField(
            model_name='invoice',
            name='old_metal_raw_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction_type',
            field=models.CharField(choices=[('payable', 'Customer Payable'), ('return', 'Return to Customer')], default='payable', max_length=10),
        ),
    ]
