# Generated by Django 6.0.3 on 2026-06-13 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_estimate_old_deduct_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='making_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='making_rate',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
