# Generated by Django 5.2.7 on 2026-06-13 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_estimate_making_rate_invoice_making_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='making_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='making_rate',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True),
        ),
    ]
