# Generated by Django 6.0.3 on 2026-07-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_estimate_making_rate_alter_invoice_making_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='invoice',
            name='igst',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
