# Generated by Django 6.0.3 on 2026-04-05 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_shop_date_format_shop_decimal_precision_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='supabase_email',
            field=models.EmailField(blank=True, db_index=True, help_text='Supabase login email', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='supabase_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Supabase auth.users.id (UUID)', max_length=255, null=True, unique=True),
        ),
    ]
