# Generated by Django 5.2.7 on 2026-04-09 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_shop_supabase_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SyncQueue',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('model_name', models.CharField(help_text="E.g., 'Shop', 'Customer'", max_length=100)),
                ('object_id', models.CharField(help_text='Local ID of the object', max_length=50)),
                ('action', models.CharField(choices=[('create', 'Create'), ('update', 'Update'), ('delete', 'Delete')], max_length=20)),
                ('payload', models.JSONField(blank=True, help_text='Data to push (for create/update if needed)', null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('failed', 'Failed'), ('synced', 'Synced')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('attempts', models.IntegerField(default=0)),
                ('last_error', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='shop',
            name='supabase_email',
            field=models.EmailField(blank=True, db_index=True, help_text='Supabase login email', max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='shop',
            name='supabase_user_id',
            field=models.CharField(blank=True, db_index=True, help_text='Supabase auth.users.id (UUID)', max_length=255, null=True, unique=True),
        ),
    ]
