# Generated by Django 6.0.3 on 2026-04-11 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_update_theme_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='shop',
            name='owner_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.CharField(blank=True, max_length=15),
        ),
    ]
