# Generated by Django 6.0.3 on 2026-04-12 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_shop_address_alter_shop_owner_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='pan_number',
            field=models.CharField(blank=True, help_text='PAN card number for invoices', max_length=20),
        ),
        migrations.AddField(
            model_name='shop',
            name='pdf_template',
            field=models.CharField(default='classic', help_text='Selected PDF invoice template: classic | standard', max_length=30),
        ),
        migrations.AddField(
            model_name='shop',
            name='watermark_logo',
            field=models.ImageField(blank=True, help_text='Custom logo image used as watermark on billing PDFs', null=True, upload_to='watermarks/'),
        ),
    ]
