# Generated by Django 6.0.3 on 2026-06-25 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_shop_pan_number_shop_pdf_template_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberingSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sequence_type', models.CharField(max_length=50)),
                ('last_number', models.PositiveIntegerField(default=0)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbering_sequences', to='accounts.shop')),
            ],
            options={
                'unique_together': {('shop', 'sequence_type')},
            },
        ),
    ]
