# Generated by Django 6.0.3 on 2026-06-27 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_numberingsequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='require_full_payment_for_delivery',
            field=models.BooleanField(default=False, help_text='Require full payment before order delivery'),
        ),
    ]
