# Generated by Django 6.0.3 on 2026-07-06 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_shop_require_full_payment_for_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='default_igst_rate',
            field=models.DecimalField(decimal_places=2, default=3.0, max_digits=5),
        ),
    ]
