# Generated by Django 6.0.3 on 2026-09-12 07:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0013_karigar_model'),
        ('customers', '0002_alter_customer_customer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('total_recipients', models.IntegerField(default=0)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('message_text', models.TextField()),
                ('media_file', models.FileField(blank=True, null=True, upload_to='marketing/banners/')),
                ('delay_seconds', models.IntegerField(default=3)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketing_campaigns', to='accounts.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient_name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('campaign', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='marketing.marketingcampaign')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='customers.customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_logs', to='accounts.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=150)),
                ('category', models.CharField(choices=[('promotional', 'Promotional Offer'), ('festival', 'Festival & Greetings'), ('scheme', 'Gold Scheme / Kitty'), ('transactional', 'Invoice & Payment'), ('custom', 'Custom')], default='promotional', max_length=30)),
                ('message_text', models.TextField(help_text='Supports {name}, {phone}, {shop_name}, {shop_phone}, {total_spent}')),
                ('media_file', models.FileField(blank=True, null=True, upload_to='marketing/templates/')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='accounts.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WhatsAppSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('instance_id', models.CharField(max_length=100, unique=True)),
                ('phone_number', models.CharField(blank=True, max_length=20, null=True)),
                ('profile_name', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('disconnected', 'Disconnected'), ('qr_ready', 'QR Ready for Scan'), ('connecting', 'Connecting'), ('connected', 'Connected'), ('expired', 'Session Expired')], default='disconnected', max_length=30)),
                ('qr_code_base64', models.TextField(blank=True, null=True)),
                ('anti_ban_delay_min', models.IntegerField(default=3, help_text='Minimum delay in seconds between messages')),
                ('anti_ban_delay_max', models.IntegerField(default=6, help_text='Maximum delay in seconds between messages')),
                ('gateway_url', models.CharField(blank=True, default='', help_text='Evolution API Server URL', max_length=255)),
                ('api_key', models.CharField(blank=True, default='', help_text='Evolution API Key', max_length=255)),
                ('last_connected_at', models.DateTimeField(blank=True, null=True)),
                ('shop', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='whatsapp_session', to='accounts.shop')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
