# Generated by Django 6.0.3 on 2026-08-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_shop_credit_note_validity_days'),
        ('payments', '0003_advancepayment_cancellation_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advancepayment',
            name='receipt_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='advancepayment',
            unique_together={('shop', 'receipt_no')},
        ),
    ]
