# Generated by Django 6.0.3 on 2026-07-10 18:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0011_shop_default_igst_rate'),
        ('customers', '0002_alter_customer_customer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldPurchaseVoucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('voucher_no', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('metal_type', models.CharField(choices=[('gold', 'Gold'), ('silver', 'Silver')], default='gold', max_length=10)),
                ('description', models.TextField(blank=True, help_text='Description of old metal article(s)')),
                ('no_of_articles', models.PositiveIntegerField(default=1)),
                ('purity', models.CharField(blank=True, help_text='e.g. 22K, 18K, 925', max_length=20)),
                ('gross_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('net_weight', models.DecimalField(decimal_places=3, default=0, max_digits=10)),
                ('rate_per_10gm', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('not_adjusted', 'Not Adjusted'), ('adjusted_invoice', 'Adjusted with Invoice'), ('adjusted_estimate', 'Adjusted with Estimate')], default='not_adjusted', max_length=30)),
                ('adjusted_invoice_no', models.CharField(blank=True, max_length=50, null=True)),
                ('adjusted_estimate_no', models.CharField(blank=True, max_length=50, null=True)),
                ('adjusted_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='old_purchase_vouchers', to='customers.customer')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_purchase_vouchers', to='accounts.shop')),
            ],
            options={
                'verbose_name': 'Old Purchase Voucher',
                'verbose_name_plural': 'Old Purchase Vouchers',
                'ordering': ['-created_at'],
            },
        ),
    ]
