# Generated by Django 6.0.3 on 2026-08-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_shop_credit_note_validity_days'),
        ('old_purchases', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldpurchasevoucher',
            name='voucher_no',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='oldpurchasevoucher',
            unique_together={('shop', 'voucher_no')},
        ),
    ]
