# Generated by Django 6.0.3 on 2026-09-02 14:26

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('old_purchases', '0002_alter_oldpurchasevoucher_voucher_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oldpurchasevoucher',
            name='date',
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
