# Generated by Django 6.0.3 on 2026-08-30 08:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0012_shop_credit_note_validity_days'),
        ('billing', '0011_creditnoteusage_applied_to_order'),
        ('customers', '0002_alter_customer_customer_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='DueEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('due_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('bill_type', models.CharField(choices=[('none', 'None'), ('invoice', 'Invoice'), ('estimate', 'Estimate')], default='none', max_length=20)),
                ('bill_number', models.CharField(blank=True, default='', max_length=100)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('partially_paid', 'Partially Paid'), ('cleared', 'Cleared')], default='pending', max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manual_due_entries', to='customers.customer')),
                ('estimate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_dues', to='billing.estimate')),
                ('invoice', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_dues', to='billing.invoice')),
                ('shop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='due_entries', to='accounts.shop')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
